name: Build

on:
  push:
    branches:
      - main
      - development
  # Trigger the workflow on any pull request
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      - name: Restore
        run: |
          dotnet restore --locked-mode
          dotnet tool restore

      - name: Build
        run: |
          dotnet build -c Release --no-restore -WarnAsError

      - name: Pack Thunderstore
        run: |
          dotnet pack -c Release --no-build -target:PackThunderstore

      - name: Upload Thunderstore artifact
        uses: actions/upload-artifact@v4
        with:
          name: thunderstore-build
          path: ./artifacts/thunderstore/*.zip

      - name: Upload nupkg artifact
        uses: actions/upload-artifact@v4
        with:
          name: nupkg-build
          path: ./artifacts/package/release/*.nupkg